n1 = input('digite seu número favorito:')
n2 = input('digite seu segundo número favorito:')
soma = int(n1) + int(n2)
#print('A soma dos seus números favoritos é:',soma)
print(f'A soma dos seus números favoritos da {soma}')