primeiro = input('Olá, qual é o seu nome?')
segundo = input('qual é o seu sobrenome?')
print('Ok!',primeiro, segundo, 'me chamo Teste e vou ter fazer umas perguntas.')
dia = input('Em que dia você nasceu?')
mês = input('Em que mês você nasceu?')
ano = input('Em que ano você nasceu?')
n1 = input('Digite seu número favorito:')
n2 = input('Digite seu segundo número favorito:')
soma = int(n1) + int(n2)
print('Você se chama',primeiro,segundo, ',' 'nasceu no',dia, 'do', mês, 'no ano de',ano,'.','E a soma dos seus números favoritos da', soma)
